FROM docker.io/zmkfirmware/zmk-build-arm:stable

RUN apt-get update && apt-get install -y --no-install-recommends python3-pip && rm -rf /var/lib/apt/lists/* && \
    pip3 install --break-system-packages west && \
    pip3 install --break-system-packages \
      -r https://raw.githubusercontent.com/zephyrproject-rtos/zephyr/v3.5-branch/scripts/requirements-base.txt
