parse_config:
  raw_binding_map:
    # Mouse
    "&msc SCRL_UP": {t: "$$mdi:mouse-scroll-wheel$$", s: "$$mdi:arrow-up-thin$$", type: text_with_symbol}
    "&msc SCRL_DOWN": {t: "$$mdi:mouse-scroll-wheel$$", s: "$$mdi:arrow-down-thin$$", type: text_with_symbol}
    "&msc SCRL_LEFT": {t: "$$mdi:mouse-scroll-wheel$$", s: "$$mdi:arrow-left-thin$$", type: text_with_symbol}
    "&msc SCRL_RIGHT": {t: "$$mdi:mouse-scroll-wheel$$", s: "$$mdi:arrow-right-thin$$", type: text_with_symbol}
    "&mmv MOVE_UP": {t: "$$mdi:mouse-outline$$", s: "$$mdi:arrow-up$$", type: text_with_symbol}
    "&mmv MOVE_DOWN": {t: "$$mdi:mouse-outline$$", s: "$$mdi:arrow-down$$", type: text_with_symbol}
    "&mmv MOVE_LEFT": {t: "$$mdi:mouse-outline$$", s: "$$mdi:arrow-left$$", type: text_with_symbol}
    "&mmv MOVE_RIGHT": {t: "$$mdi:mouse-outline$$", s: "$$mdi:arrow-right$$", type: text_with_symbol}
    "&mkp MB1": {t: "$$mdi:cursor-default-click-outline$$", s: 1, type: text_with_symbol}
    "&mkp MB2": {t: "$$mdi:cursor-default-click-outline$$", s: 2, type: text_with_symbol}
    "&mkp MB3": {t: "$$mdi:cursor-default-click-outline$$", s: 3, type: text_with_symbol}

    # Bluetooth
    "&bt BT_CLR": {t: "$$mdi:bluetooth$$", s: "$$mdi:close-thick$$", type: text_with_symbol}
    "&bt BT_SEL 0": {t: "$$mdi:bluetooth-connect$$", s: "0", type: text_with_symbol}
    "&bt BT_SEL 1": {t: "$$mdi:bluetooth-connect$$", s: "1", type: text_with_symbol}
    "&bt BT_SEL 2": {t: "$$mdi:bluetooth-connect$$", s: "2", type: text_with_symbol}
    "&bt BT_SEL 3": {t: "$$mdi:bluetooth-connect$$", s: "3", type: text_with_symbol}
    "&bt BT_SEL 4": {t: "$$mdi:bluetooth-connect$$", s: "4", type: text_with_symbol}

    # Macros
    "&macro_int5_esc": _ESC
    "&macro_send_exit": '"exit"'
    "&macro_abc": INT5
    "&macro_aiu": INT4

    "&bootloader": "&bootloader"
